### ISSUE TITLE
Cannot add android account

### ISSUE THREAD

**Issue by maxmopp** [etesync/android#102]
Things worked nicely until I deleted the account, reinstalled my server and tried to readd the account to the phone. I can log in and enter the encryption pwd but "FINISH" does not complete.
Different users on the same phone with same error. Server reinstall, Android Clear Storage and app reinstall did not change anything.
A different phone could finish the setup with the same server + credentials.

logcat: 
[https://pastebin.com/cbVczpGG](https://pastebin.com/cbVczpGG)

Android 9/LOS 16

**Comment by maxmopp** [comment]
More info: seems to be a problem with the Id for the accounts.db etesync 
`E SQLiteDatabase: Error inserting name=max _id=15 last_password_entry_time_millis_epoch=1575810419309 type=com.etesync.syncadapter`
checking my accounts.db there is another account with id 15 (non etesync)

**Comment by tasn** [comment]
You shouldn't be adding the account from outside of the EteSync app (it should be blocked iirc). You should also not clear android storage. The app doesn't know how to recover from that (because the accounts still remain on the device).

Could you please try uninstalling the app again, reinstalling and adding the account then? Please also share a logcat of that.

Thanks!

**Comment by maxmopp** [comment]
Sorry for the late answer. I think the probleme was that I restored the accounts db directly from a sqldump moving from device to device. I saw the same happening with other account. Clearing the complete db solved the problem. Sorry for the mess!

**Comment by tasn** [comment]
Ahh, I was bitten by that before too! :)

No worries.
