### ISSUE TITLE
Support integration with Tasks.org Android app

### ISSUE THREAD

**Issue by devurandom** [etesync/android#112]
I have the EteSync Android app installed on my phone as well as Tasks.org. The EteSync app has created a bunch of accounts and keeps them in sync with the servers. However, under "Tasks" it display nothing and when opening the associated hamburger menu it offers to "Install OpenTasks".

On the other hand I have to set up Tasks.org again with the same credentials that I already provided to the EteSync app, and it implements synchronisation itself. Providing my EteSync credentials to a third party application also feels like giving that application unnecessary control over all of my data without me having an option to limit access to the bits it really needs (namely the tasks).

It would be great if Tasks.org could use the data synced through the EteSync app and its accounts.

See-Also: https://github.com/tasks/tasks/issues/952

**Comment by tasn** [comment]
There's also: https://github.com/tasks/tasks/issues/554

I agree with (and share) your concerns regarding giving your credentials to 3rd party apps. This is indeed usually a bad idea. We would definitely not want this to become the norm, which is why we are working on improving the protocol to make it possible to share only specific journals with different devices of the same user.

As far Tasks.org: I personally put my password there. I think that given it's OSS it's more trustworthy than just a random piece of software. Though as I said, I share your concerns and this is something we are working on addressing.

Regarding this ticket: I'm closing it because there are already two tickets on Tasks.org's issue tracker, and since there is nothing we can do on our side other than updating the protocol, which we already are doing. :)
