### ISSUE TITLE
Long press on calendar does not delete

### ISSUE THREAD

**Issue by wireddude** [etesync/android#16]
The [FAQ](https://www.etesync.com/user-guide/) states

" in order to delete a calendar, long-press on the wanted calendar item. A menu will pop-up, on which you should click "Delete".

I cannot get this to work, or to delete an already imported calendar. On Google Pixel, Android O.

**Comment by tasn** [comment]
Oops, sorry! It's a mistake in the FAQ (it's a bit outdated on this topic,
it seems).

To delete a calendar tap it, and from the calendar page you can then hit
the edit (pencil) button at the top right corner, and then the delete
(trash bin) button to delete it.

I'll make sure to update the FAQ tomorrow, thanks for letting me know!

P.s, I'd recommend referring to the user guide rather than the FAQ for
usage instructions.

On 20 Nov 2017 01:56, "Wired Dude" <notifications@github.com> wrote:

The FAQ <https://www.etesync.com/user-guide/> states

" in order to delete a calendar, long-press on the wanted calendar item. A
menu will pop-up, on which you should click "Delete".

I cannot get this to work, or to delete an already imported calendar. On
Google Pixel, Android O.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/etesync/android/issues/16>, or mute the thread

**Comment by tasn** [comment]
Thanks, fixed!
