### ISSUE TITLE
No permission to import from file

### ISSUE THREAD

**Issue by Terrance** [etesync/android#249]
Import > From File fails with the following message:

> **Import Failed**
> 
> Reason: Reading storage permission is required for import.

However, the app never asks for the storage permission to be granted, nor do I seem to be able to grant it in Android's app settings.

<img src="https://github.com/etesync/android/assets/4025899/0f390aa4-6b49-40de-96cc-37a8ff7a7412" width="300">

Device is a OnePlus Nord CE, Android 13, EteSync 2.4.3.

**Comment by jahway603** [comment]
I was just about to file this as an Issue as I'm experiencing the same.

**Comment by jahway603** [comment]
I hate medium, because they never let you read anything, but it appears that the Android Permission being used, `android.permission.READ_EXTERNAL_STORAGE`, has been replaced in Android 13+
https://medium.com/@maydin/how-to-migrate-read-external-storage-permission-to-read-media-images-permission-for-android-13-ab99de39318

**Comment by jahway603** [comment]
This Issue is related to Issue https://github.com/etesync/android/issues/199

**Comment by jahway603** [comment]
Found more info here from Google, https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

I have tried each of the three new permissions, but none of them are working to let the Import feature work...

**Comment by Terrance** [comment]
Looks like this is now fixed as of #254 and 2.4.4.

**Comment by tasn** [comment]
Thanks for closing the ticket, I missed that!
