### ISSUE TITLE
Enable import of mixed calendars/task lists

### ISSUE THREAD

**Issue by DeWir3** [etesync/android#70]
Coming from Owncloud's CalDAV implementation, I could not import the .ics files I exported from there in the app. The issue seems to be that they contain calendar events as well as ToDos. It would be very helpful if the app could automatically filter out all ToDo elements from the .ics when importing into a calendar and vice versa.

**Comment by tasn** [comment]
I just verified and it seems to work. They are correctly skipped. Either something has changed since you posted (I changed a few things there), or maybe the example I'm testing with is insufficient.

Could you please create a temporary calendar and try to import the file again and reopen this ticket if it's indeed broken?

Thanks.

**Comment by DeWir3** [comment]
I can confirm it's working now. Thanks! Tested it with the same file that wasn't working before and it went through without an issue.

**Comment by tasn** [comment]
Great to hear, thanks for the update!
