### ISSUE TITLE
How to enable cleartext option?

### ISSUE THREAD

**Issue by stevesbrain** [etesync/android#81]
Hey there,

Previously had an internally hosted cleartext server which no longer works after an app update. Is there an option to re-enable this? I consistently get

> CLEARTEXT communication to <server> not permitted by network security policy.

I can't see any option to permit this, but am presuming it's android-side (as an older docker image that worked previously no longer works). Any assistance would be great :)

**Comment by tasn** [comment]
I guess something changed on your Android device as I haven't changed anything related to that. Additionally, it still works on my Android 8.1 device (though only tested with debug builds, so maybe that affects things.

Anyhow, could you please try: https://stosb.com/~tom/etesync-cleartext.apk ? It's signed with the release key so should just install cleanly over the Google Play version if you have that one installed.

**Comment by stevesbrain** [comment]
@tasn - thanks for weighing in, and for the work you do! In the mean time I'd switched back to my paid account, but would still like to troubleshoot the issue (especially given you said nothing had changed). The apk you linked worked without any issue - I was able to login etc as I could previously.

In terms of "what's changed", I haven't performed any system updates on my phone; still working on Android 9 (Pixel 2XL, build PQ2A.190405.003), and running etesync 1.4.10. In this time I had upgraded the Docker image of the skeleton server to a newer version, however, I've since reverted back to the previous docker image I was using and the same issue persists. I would have queried if there was a database flag that might be causing this - except that your linked build worked fine. What additional info can I provide for you, or do you have any possible clues from this so far? Thanks :)

**Comment by tasn** [comment]
It looks like it was always [a requirement for Android P (9.0)](https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html). I never noticed it because I'm developing on a 8.1 device and using my 9.0 device for testing against the production server (which uses HTTPS).
I'll release a version with the fixes in a bit, thanks for testing this.

I have no idea what could have caused it to work and then not on your device. Have you maybe upgraded the app version? It could be that I updated a dependency at some point that may have added support for this configuration sometime in the last few months.

**Comment by stevesbrain** [comment]
Hmm, very odd! I'd been using the play store version, so had been updating whenever that updated, but only noticed the issue when I went to add a new calendar this week (it didn't produce an error whilst syncing), but no idea when it started (and i subsequently tested trying to add that account fresh etc). Either way, appreciate you solving it and explaining - I'll probably just keep using the hosted version with my wife for the moment, but nice to know I can fall back to self hosted again if I choose to :)
