### ISSUE TITLE
Could this work with orgzly?

### ISSUE THREAD

**Issue by igoralmeida** [etesync/android#87]
I see there has been some interest in getting orgzly to work with webdav (https://github.com/orgzly/orgzly-android/issues/38). I don't fully understand how etesync has diverged, so I thought I'd ask for posterity: would that work seamlessly with etesync, or would it be easier to have this app provide some kind of "file API" (for the ["local storage" repository](http://www.orgzly.com/help#489bf92)) for orgzly, since it persists data to .org files?

**Comment by tasn** [comment]
It most definitely can, and as a heavy use of orgzly, it's something I was hoping to implement at some point. :) I'm happy to assist anyone who's up for the task. It shouldn't be too hard since we already have a Kotlin implementation of the protocol.

With that being said, EteSync (and DAVx5) already implements [the opentasks protocol](https://github.com/dmfs/opentasks). Maybe Orgzly should implement this instead of DAV and etesync directly? Or at least in addition?

**Comment by reyman** [comment]
It probably helps, there is a PR actually for webdav : https://github.com/orgzly/orgzly-android/pull/580

**Comment by tasn** [comment]
Webdav PR: wow, it's very simple. Maybe it's worth it to add EteSync support sooner rather than later. Making it in a way that's not compatible with the current tasks system would be very easy. Writing an adapter: slightly harder. Though I guess writing an adapter is worth it. Either way, this looks like two day's work, maybe slightly more because we would need to make the etesync encryption and sync code reusable and put it in a library.

I think OpenTasks support is still a better idea, but it's good to see it's quite easy to implement an orgzly plugin.

**Comment by igoralmeida** [comment]
Thanks, commented there. Maybe close this issue until something specific to etesync pops up.

**Comment by tasn** [comment]
OKie.

**Comment by tasn** [comment]
As of the latest version of Tasks.org EteSync is now supported as a backend. You can get it now from Google Play and soon from f-droid. We will also release a blog post about it soon. I think Tasks.org is better than orgzly. :)

Either way, the code to add EteSync was quite small, so adding to orgzly could also be done if wanted.

Tasks.org's repo: https://github.com/tasks/tasks/

**Comment by reyman** [comment]
I try that NOW ! =)

**Comment by tasn** [comment]
:tada: 

One thing though, in order to use it in Tasks.org from Google Play you would need to unlock Pro (as low as $1 a year), or you can build yourself/wait for the f-droid build if you would rather not give your card details to Google, because there it will already be included without needing to unlock pro.

**Comment by tasn** [comment]
Just a quick update: F-Droid finally built Tasks.org's latest version, so you can now get it from f-droid too!
Relevant blog post: https://blog.etesync.com/tasks-org-adds-etesync-support/
